version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    docker:
      - image: cimg/node:18.8.0
    steps:
      - checkout

      - node/install-packages:
          pkg-manager: yarn

      - run:
          name: Run unit tests
          command: yarn test

workflows:
  default-workflow:
    jobs:
      - test
